### ISSUE TITLE
Lot of 404 errors / CrowdSec ban me

### ISSUE THREAD

**Issue by EVOTk** [nextcloud/contacts#3021]
### Describe the bug

I also have a lot of 404 errors. I think it's related to the lost avatar of my contact
CrowdSec banned me because of this

### Steps to reproduce

1. Go to Contacts App
2. Scroll Contacts view
3. See Console, lot of 404 error

### Expected behavior

Do not have a 404 error when viewing my contacts

### Actual behavior

404 error

![image](https://user-images.githubusercontent.com/45015615/194425956-bc43bbde-2390-4a28-933e-64f210bce477.png)

### Contact version

4.2.2

### Operating system

OMV - Debian 11

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database

MariaDB

### Additional info

Server : 
    Docker [Linuxserver php8](https://github.com/linuxserver/docker-nextcloud/tree/php8)
    Nextcloud : 24.0.6
    Contacts : 4.2.2

Desktop : 
    OS: Windows 10
    Browser : Firefox 105

My reverse Proxy : 
```
192.168.2.42 - - [07/Oct/2022:00:01:18 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/14FF37C0-C83C-4CB5-9091-269A9337D362.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:18 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A8BDF343-8283-45EA-93BE-320EC7FC8113.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:18 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/commerces/FFB7317A-EECE-4A1E-A231-76497C232589.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/41DC030F-6573-4888-8120-7FD52ED7C3A8.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CE387EA7-2C4D-4F99-92B6-3FFB316BF985.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/connaissances/9DA090D8-D40E-406C-B8D5-E6D73B2FDA03.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/autres/FCA2429B-3819-455C-BB04-002980D4C7EE.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:20 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
```

Console , Firefox 105 : 

```
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.4.0 core-common.js:2:5520444
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
core-common.js:2:482560
Proxying an event bus of version 2.1.1 with 1.3.0 contacts-main.js:2:29456
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 3 core-main.js:2:67484
Initial state loaded defaultProfileState HOME contacts-main.js:2:4847563
Initial state loaded localesState 
Array(750) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
contacts-main.js:2:4847621
OCA.Search is deprecated. Please use the unified search API instead core-main.js:2:13191
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:2:67484
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 core-main.js:2:67484
Proxying an event bus of version 2.1.1 with 1.3.0 notifications-main.js:2:29334
Loading theming data for notification bell styling notifications-main.js:2:1200310
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:2:67484
Registering notifications container as a menu notifications-main.js:2:1200548
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 core-main.js:2:67484
Notifications permissions granted notifications-main.js:2:1205484
Polling interval updated to 30000 App.vue:355
Started background fetcher as session_keepalive is enabled notifications-main.js:2:1201985
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
session heartbeat polling started core-main.js:2:54335
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». menu.js:99:26
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:2:67484
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 5 core-main.js:2:67484
Got notification data notifications-main.js:2:1204049
Polling interval updated to 30000 App.vue:355
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 67 core-main.js:2:67484
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/D35F7124-D130-44FD-A696-1528433D8E81.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/14D7F41C-3220-4872-B47C-EA49D84B1849.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/F5775E3E-4542-4C32-9F97-9DE1DDEE76E9.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/385BF09B-7AEC-4720-96BD-B36945924612.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/304EB99D-62D3-4974-A6F5-04DC47659F01.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/qnap/EF65273A-3736-48C8-914A-A6434DE5BFAC.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/812F7683-333D-4EDF-B792-B4F9EC9710F2.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E89A7343-B956-40BD-BFA8-7630186F6906.vcf?photo ListItemIcon.js:2:7798
Masonry reflow contacts-main.js:2:4974060
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/6D18E6D3-6E5E-4D17-9A11-669BB0ED25EF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0BC3E162-E506-4A17-B394-E84DF1C1796C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/008882E3-9537-4765-A638-32AF57801F8F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/0051CBCC-DCB1-4B3A-BF64-F2F8828F0079.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/1E71B851-F0EF-4089-8BBD-26E23683912F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A74CD824-DC83-4A01-82D4-A5746CF48033.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/5588DC57-EFF5-402F-B8DD-272E037F1045.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/81A5EF0B-2F7B-41CF-8815-C3A38D972056.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0A2991AF-0935-46D2-99F9-46F79BA67860.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/816ABA2B-F03A-414D-8C56-173F83A64222.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/8D1E0BD9-55D4-4C65-A187-21D79E264A2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/8A7D7DFE-494A-4E10-963D-96498291E526.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FC3CD999-3795-4056-88D6-19E3B55AC1CE.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/qnap/EF65273A-3736-48C8-914A-A6434DE5BFAC.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E89A7343-B956-40BD-BFA8-7630186F6906.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0BC3E162-E506-4A17-B394-E84DF1C1796C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/008882E3-9537-4765-A638-32AF57801F8F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/0051CBCC-DCB1-4B3A-BF64-F2F8828F0079.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/1E71B851-F0EF-4089-8BBD-26E23683912F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A74CD824-DC83-4A01-82D4-A5746CF48033.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/5588DC57-EFF5-402F-B8DD-272E037F1045.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/81A5EF0B-2F7B-41CF-8815-C3A38D972056.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0A2991AF-0935-46D2-99F9-46F79BA67860.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/816ABA2B-F03A-414D-8C56-173F83A64222.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/8D1E0BD9-55D4-4C65-A187-21D79E264A2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/8A7D7DFE-494A-4E10-963D-96498291E526.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FC3CD999-3795-4056-88D6-19E3B55AC1CE.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/5588DC57-EFF5-402F-B8DD-272E037F1045.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/816ABA2B-F03A-414D-8C56-173F83A64222.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/8D1E0BD9-55D4-4C65-A187-21D79E264A2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/8A7D7DFE-494A-4E10-963D-96498291E526.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/81A5EF0B-2F7B-41CF-8815-C3A38D972056.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0A2991AF-0935-46D2-99F9-46F79BA67860.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FC3CD999-3795-4056-88D6-19E3B55AC1CE.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/642997F8-7AE6-4407-A579-2D9D383F68D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo ListItemIcon.js:2:7798
GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo
[HTTP/2 404 Not Found 73ms]

	
GET
	https://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo=
État
404
Not Found
VersionHTTP/2
Transfert994 o (taille 0 o)
Politique de référentsame-origin
Priorité de la requêteLow

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo
[HTTP/2 404 Not Found 124ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo
[HTTP/2 404 Not Found 263ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo
[HTTP/2 404 Not Found 90ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo
[HTTP/2 404 Not Found 133ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo
[HTTP/2 404 Not Found 155ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo
[HTTP/2 501 Not Implemented 222ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo
[HTTP/2 404 Not Found 178ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo
[HTTP/2 404 Not Found 201ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo
[HTTP/2 404 Not Found 261ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo
[HTTP/2 404 Not Found 262ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo
[HTTP/2 404 Not Found 273ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo
[HTTP/2 404 Not Found 306ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo
[HTTP/2 404 Not Found 292ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/642997F8-7AE6-4407-A579-2D9D383F68D4.vcf?photo
[HTTP/2 404 Not Found 332ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo
[HTTP/2 404 Not Found 311ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/mdecine/6A96216D-66BA-404A-AA8C-469ED524C355.vcf?photo
[HTTP/2 404 Not Found 350ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/509D2C57-7B9D-4EDF-9748-502F9694DB8F.vcf?photo
[HTTP/2 404 Not Found 375ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/A03D1C72-A111-4CB7-863D-1A084F17698E.vcf?photo
[HTTP/2 404 Not Found 361ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/A7504ADC-F39C-41D5-BB13-89235ECE0E5D.vcf?photo
[HTTP/2 404 Not Found 409ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/14FF37C0-C83C-4CB5-9091-269A9337D362.vcf?photo
[HTTP/2 404 Not Found 438ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A8BDF343-8283-45EA-93BE-320EC7FC8113.vcf?photo
[HTTP/2 404 Not Found 468ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/FCA2429B-3819-455C-BB04-002980D4C7EE.vcf?photo
[HTTP/2 404 Not Found 490ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/FFB7317A-EECE-4A1E-A231-76497C232589.vcf?photo
[HTTP/2 404 Not Found 480ms]

Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/642997F8-7AE6-4407-A579-2D9D383F68D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/6A96216D-66BA-404A-AA8C-469ED524C355.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/A03D1C72-A111-4CB7-863D-1A084F17698E.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/509D2C57-7B9D-4EDF-9748-502F9694DB8F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/A7504ADC-F39C-41D5-BB13-89235ECE0E5D.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/14FF37C0-C83C-4CB5-9091-269A9337D362.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A8BDF343-8283-45EA-93BE-320EC7FC8113.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FFB7317A-EECE-4A1E-A231-76497C232589.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/FCA2429B-3819-455C-BB04-002980D4C7EE.vcf?photo ListItemIcon.js:2:7798
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo
[HTTP/2 501 Not Implemented 254ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo
[HTTP/2 404 Not Found 198ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo
[HTTP/2 404 Not Found 353ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo
[HTTP/2 404 Not Found 352ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo
[HTTP/2 404 Not Found 349ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo
[HTTP/2 404 Not Found 346ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo
[HTTP/2 404 Not Found 345ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo
[HTTP/2 501 Not Implemented 490ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo
[HTTP/2 404 Not Found 342ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo
[HTTP/2 404 Not Found 494ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo
[HTTP/2 404 Not Found 494ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo
[HTTP/2 404 Not Found 615ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo
[HTTP/2 404 Not Found 614ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo
[HTTP/2 404 Not Found 615ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo
[HTTP/2 404 Not Found 614ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo
[HTTP/2 404 Not Found 634ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo
[HTTP/2 404 Not Found 642ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo
[HTTP/2 404 Not Found 624ms]

Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo ListItemIcon.js:2:7798
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
```

**Comment by EVOTk** [comment]
Also related to https://github.com/nextcloud/contacts/issues/3078

**Comment by arnowelzel** [comment]
I can confirm this. It seems this is the way how the contact app works: it will try to load the image for each contact and for those contacts where there is no image stored there will be an 404 error instead of a generated (and probably cached) placeholder.

**Comment by EVOTk** [comment]
Attention, I just realized a few things, I had the impression that some contacts had disappeared from my Nextcloud, and indeed ...

When I'm on the page of a contact and this problem occurs, then I unban from Crowdsec, when I come back on Nextcloud, the contact that I consulted during the banishment by Crowdsec is no longer present in my contact list!

**Comment by dariolah** [comment]
Same issue, lots of unnecessary 404's triggering security app monitoring logs.

Expected behavior: if contact doesn't have picture don't make http request for it.

Second best: if contact doesn't have picture use default picture. E.g. transparent, so initials are seen?

4xx responses should not be used as normal way of working like everything is OK.

**Comment by arnowelzel** [comment]
As mentioned in #3078 @summersab created a "patch app" which can be installed to fix this problem until it is solved in the contacts app itself:

https://github.com/nunimbus/contacts_avatar_patch

Download the files and put them to `/apps/contacts_avatar_patch` in your Nextcloud installation. Then you should see a disabled "Contacts Avatar Patch" app. When enabling it, the contact images should displays as before without 404 errors.

![image](https://user-images.githubusercontent.com/6613614/206849827-54162d9c-5b24-4ba8-9dce-2724a64df4bf.png)

**Comment by summersab** [comment]
Hmm... I didn't realize that the app was supposed to grab custom avatars for those users who are stored in the address book. That makes sense, though. I'll give that a look this week to hopefully update my patch and find the root cause in the NC code.

**Comment by LaurenceJJones** [comment]
We have a WIP whitelist for contacts app. Just need some testing. [Here](https://raw.githubusercontent.com/LaurenceJJones/hub/a984e6f47004743158e5bc590c70780ef6368177/parsers/s02-enrich/crowdsecurity/nextcloud-whitelist.yaml)
```
curl -s https://raw.githubusercontent.com/LaurenceJJones/hub/a984e6f47004743158e5bc590c70780ef6368177/parsers/s02-enrich/crowdsecurity/nextcloud-whitelist.yaml > /etc/crowdsec/parsers/s02-enrich/nextcloud-whitelist.yaml
```

**Comment by flurmind** [comment]
Same issue with fail2ban!

**Comment by LaurenceJJones** [comment]
> Same issue with fail2ban!

This is now resolved for Crowdsec

**Comment by arnowelzel** [comment]
This happens with Contacts 5.1.0 when I scroll down the contact list:

![image](https://user-images.githubusercontent.com/6613614/216819316-9956f87c-fbb7-4abe-a837-381286d24c28.png)

The reason for these many 404 errors are still the contact images. For every contact there is a request like this:

`https://nextcloud.0x0c.de/remote.php/dav/addressbooks/users/awelzel/contacts/C74B935A-2600-0001-1CF1-6B30CE9015B9.vcf?photo`

However the respective contacts don't have any image. It seems the contact app just tries to load images regardless if there is an image or not.

The best solution would be not to try load an image if there is none - and since the contact app should know exactly if there is an image or not, this should be possible.

**Comment by kladderadeng** [comment]
Thanks @LaurenceJJones for the Whitelist for Crowdsec.
But I hope this can get fixed in Nextcloud in one way or another (still exists in 26.0.1). Anyway, Thanks to everyone improving Nextcloud, whether it is a fix in Nextcloud or a workaround like the whitelist 👍

**Comment by arnowelzel** [comment]
No - still not solved in Nextcloud 27.0.2. I don't understand, why the contact list does not know that there is no contact picture **without** asking the server all the time?

![image](https://github.com/nextcloud/contacts/assets/6613614/98823506-1292-42c5-a303-e4c9a70d9d6b)

**Comment by DonkeeeyKong** [comment]
Hello, are there any news on this? I'm on a fresh installation of Nextcloud 28 and I get banned by fail2ban every time I open the contacts page. For now I had to disable fail2ban to be able to use nextcloud - but that's not a good solution...
Clients like Gnome Contacts seem to get 404 errors as well when syncing - though not as many as the contacts page.

**Comment by arnowelzel** [comment]
No, still as usual with Nextcloud 28.0.3:

![image](https://github.com/nextcloud/contacts/assets/6613614/c9f3289d-00d4-4abf-a4f0-6c0a14c7d2eb)

Unfortunately I don't have the time to get involved with the code. But technically it should not be too hard to solve:

1. Every address should have a flag to indicate if there is a photo or not (the backend knows about this, otherwise it would not respond with 404 if a photo is requested for a contact without a photo).
2. The frontend will only request the photo URL for a contact, if the flag "has a photo" is set.
3.

**Comment by DonkeeeyKong** [comment]
That's a problem. I had fail2ban set up to look for 4xx errors in the npm logs. In order to be able to use nextcloud I had to disable that line of defense. 
I have tried to set up crowdsec on my server instead - sadly so far without success. 

> No, still as usual with Nextcloud 28.0.3:
> 
> ![image](https://private-user-images.githubusercontent.com/6613614/312568419-c9f3289d-00d4-4abf-a4f0-6c0a14c7d2eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzY5MzksIm5iZiI6MTcxMTEzNjYzOSwicGF0aCI6Ii82NjEzNjE0LzMxMjU2ODQxOS1jOWYzMjg5ZC0wMGQ0LTRhYmYtYTRmMC02YzBhMTRjN2QyZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTk0MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI3N2I1Yjg0ZDRiYTNkNzA3NGI1Y2RhNDdlYjQ1NTIyNmFhNjcxYzg1ODM4NGNjYWFlNGRlYTE5OWQyMzgyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ir-8SJbvL4mt68CfHzbok3FRsWWgw2CX1Q4ytqNaNcw)
> 
> Unfortunately I don't have the time to get involved with the code. But technically it should not be too hard to solve:
> 
>     1. Every address should have a flag to indicate if there is a photo or not (the backend knows about this, otherwise it would not respond with 404 if a photo is requested for a contact without a photo).
> 
>     2. The frontend will only request the photo URL for a contact, if the flag "has a photo" is set.
That's a problem. I had fail2ban set up to look for 4xx errors in the npm logs. In order to be able to use nextcloud I had to disable that line of defense. 
I have tried to set up crowdsec on my server instead - sadly so far without success.

**Comment by DonkeeeyKong** [comment]
> No, still as usual with Nextcloud 28.0.3:
> 
> ![image](https://private-user-images.githubusercontent.com/6613614/312568419-c9f3289d-00d4-4abf-a4f0-6c0a14c7d2eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzY5MzksIm5iZiI6MTcxMTEzNjYzOSwicGF0aCI6Ii82NjEzNjE0LzMxMjU2ODQxOS1jOWYzMjg5ZC0wMGQ0LTRhYmYtYTRmMC02YzBhMTRjN2QyZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTk0MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI3N2I1Yjg0ZDRiYTNkNzA3NGI1Y2RhNDdlYjQ1NTIyNmFhNjcxYzg1ODM4NGNjYWFlNGRlYTE5OWQyMzgyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ir-8SJbvL4mt68CfHzbok3FRsWWgw2CX1Q4ytqNaNcw)
> 
> Unfortunately I don't have the time to get involved with the code. But technically it should not be too hard to solve:
> 
>     1. Every address should have a flag to indicate if there is a photo or not (the backend knows about this, otherwise it would not respond with 404 if a photo is requested for a contact without a photo).
> 
>     2. The frontend will only request the photo URL for a contact, if the flag "has a photo" is set.

That's a problem. I had fail2ban set up to look for 4xx errors in the npm logs. In order to be able to use nextcloud I had to disable that line of defense.
I have tried to set up crowdsec on my server instead - sadly so far without success.

**Comment by nderambure** [comment]
Still have this problem in Nextcloud 29.0.10, It's a 2 years bug...
CrowdSec bans any attempt to go to the contact app, tons of 404 are triggerring the scenario http-probing : 
https://app.crowdsec.net/hub/author/crowdsecurity/scenarios/http-probing

And the 404 grows with contacts creations, so even fixing the limit higher is not a solution, we need to disable this scenario which is counter productive :'(

**Comment by SebastianKrupinski** [comment]
Fixed. https://github.com/nextcloud/server/pull/49839

**Comment by SebastianKrupinski** [comment]
Additional Fix https://github.com/nextcloud/contacts/pull/4249

**Comment by nderambure** [comment]
Thank you @SebastianKrupinski !

**Comment by SebastianKrupinski** [comment]
You're welcome! I do what i can 😄

**Comment by arnowelzel** [comment]
Thank you, @SebastianKrupinski!

**Comment by EVOTk** [comment]
Thx @SebastianKrupinski  !
