### ISSUE TITLE
Contact details not displayed when selected using 'Quick' search icon

### ISSUE THREAD

**Issue by ds4a** [nextcloud/contacts#395]
### Steps to reproduce
NC 12.0.3.3
1. When not in contacts app (e.g Files app), use contact quick search (icon just to left of user avatar).
2. Search for contact
3. Select details icon 'i'.

### Expected behaviour
Contacts app displayed, with details of specific selected user displayed.
This is the behaviour exhibited when the contacts app is the selected app in use.

### Actual behaviour
Contact app displayed, main / standard all contacts listing displayed in alphabetical order.

### General server configuration

**Operating system:** Linux nc.example.com 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imagick
 - intl
 - json
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install: previous NC 11.0.4 

**Where did you install Nextcloud from: cli updater

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - apporder: 0.4.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "apps_paths": [
        {
            "path": "\/var\/www\/nextcloud\/apps",
            "url": "\/apps",
            "writable": true
        }
    ],
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "loglevel": 2,
    "logtimezone": "UTC",
    "maintenance": false,
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "noreply",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "singleuser": false,
    "updater.release.channel": "stable",
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updatechecker": true,
    "htaccess.RewriteBase": "\/",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Ubuntu linux 14.04

**Comment by irgendwie** [comment]
Can reproduce, thanks for reporting the issue!

**Comment by Henni** [comment]
Was this fixed in the meantime? I can't reproduce it on master...

**Comment by irgendwie** [comment]
@ds4a Would you mind re-checking if this still occurs on your instance?
Feel free to reopen the issue then, otherwise I'm also not able to reproduce this anymore.

**Comment by ds4a** [comment]
I can confirm this is now resolved for me also. No new release install required.

**Comment by rollanders** [comment]
I can confirm this is still present. NC 15.02, Contacts 3.01. 
After searching a contact in the upper right corner, and selecting "details" opens a white page in Contacts.
