### ISSUE TITLE
Shared calendar doesn't show up in team overview

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/contacts#4127]
### Steps to reproduce

I am not sure, if this should better be a report for nextcloud/circles.:

1. I share a calendar with a team/circle
2. I switch to contacts.
3. When I look at my team, there are all the other ressources listed - but not the calendar.

### Expected behavior

Calendar listed like all the other ressources

### Actual behaviour

Calendar doesn't show up

### Calendar app version

4.7.16

### CalDAV-clients used

-

### Browser

Firefox 130

### Client operating system

Win10

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
I don't think we've implemented that yet - @hamza221 do you know more about this?

**Comment by alexanderdd** [comment]
IMO you should also be able to **create** a new calendar from the Teams page. Should this be tracked here as well, or should I open a separate issue?

**Comment by hamza221** [comment]
> IMO you should also be able to **create** a new calendar from the Teams page. Should this be tracked here as well, or should I open a separate issue?

A separate issue would be better

**Comment by hamza221** [comment]
Hello, 
It looks like this is still not implemented, and I think it would be a good addition 
cc @nextcloud/server-frontend
