### ISSUE TITLE
Contact could not be saved

### ISSUE THREAD

**Issue by DanLeonelli** [nextcloud/contacts#462]
### Steps to reproduce
1. Create new contact
2. Add more than 5 fields
3. Try with notes/anniversary/adding photo

### Expected behaviour
Contact saved

### Actual behaviour
Error: "Contact could not be saved"

### Server configuration

**Operating system**: 

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 12.0.4

**Contacts version:** (see Nextcloud apps page) 2.0.1

**Updated from an older Nextcloud or fresh install:** Fresh install

<img width="421" alt="screen shot 2018-01-23 at 5 53 52 pm" src="https://user-images.githubusercontent.com/35517527/35305373-17a30fb2-0067-11e8-844c-373637cf1785.png">

I've even tried clearing the cache (as mentioned in the closed topics regarding this issue), using other browser (Safari and Chrome) and I get the same error...

**Comment by skjnldsv** [comment]
We'll need the console log of your browser please :)

**Comment by skjnldsv** [comment]
Bump?

**Comment by jovanie** [comment]
I have a similar issue too: my instance is freshly updated and I can't create a contact and any info I put into a new contact is lost shortly after. Also, I can't click on any other contact. I'm not sure how to get a console log.

**Comment by skjnldsv** [comment]
@jovanie what browser do you use? :)

**Comment by jovanie** [comment]
Chrome!

**Comment by skjnldsv** [comment]
You can press F12 to see the browser log then :)
Open it then reload the page and edit your contact

**Comment by pinowthebird** [comment]
I have the same issue, and I'm using Chrome.

**Comment by skjnldsv** [comment]
@pinowthebird same answer, I need your browser log :)

**Comment by pinowthebird** [comment]
"Luckily" it occurs often.
![image](https://user-images.githubusercontent.com/36229718/36776490-496ca754-1c66-11e8-895b-fbf0263cdcd3.png)

**Comment by skjnldsv** [comment]
@pinowthebird can you post the response of the first 400 put failure request please?

**Comment by pinowthebird** [comment]
It seems to happen when I switch between contacts.

![image](https://user-images.githubusercontent.com/36229718/36776856-91d28210-1c67-11e8-971f-50cb4dedcd51.png)

**Comment by pinowthebird** [comment]
![image](https://user-images.githubusercontent.com/36229718/36777373-88859f42-1c69-11e8-9550-de53e42b0bbb.png)

**Comment by skjnldsv** [comment]
One more step, click the failed request and click the "response tab". Sorry :see_no_evil:

**Comment by pinowthebird** [comment]
No problem, I was already on it.

![image](https://user-images.githubusercontent.com/36229718/36777592-58191d92-1c6a-11e8-9490-f765813cc72c.png)

**Comment by skjnldsv** [comment]
Ah! Found it :D 
Well, you have a failing contact, probably from a previous install?
Anyway, I'll suggest that you download it, and then import it again to generate a new uid.

**Comment by pinowthebird** [comment]
Both my install and the contacts are fresh.

**Comment by pinowthebird** [comment]
Also, I get the same error after deleting and recreating the contact.

**Comment by skjnldsv** [comment]
@pinowthebird The import works?

**Comment by pinowthebird** [comment]
I deleted it, and started from scratch. That should result in a new UID as well?

If I export, delete and import again, then it fails. I get the following response:
"Calendar object with uid already exists in this calendar collection."

I did now notice that the Calendar has now two birthday events for the unexisting contact.

**Comment by pinowthebird** [comment]
I managed to start from scratch. And after a lot of testing I finally discovered what causes this issue:
**Adding both a birthday and an anniversary.** I haven't used nor tested date of death.

"Calendar object with uid already exists in this calendar collection."

**Comment by skjnldsv** [comment]
Export, delete your contact, edit the vcf file and remove the UID line, re-import again.

**Comment by pinowthebird** [comment]
The issue remains. And that's because that contact isn't the issue. 

The issue is every contact with both an anniversay and birthday. I've tried this with multiple contacts now. Both from scratch and adding an anniversary to contacts that already have a birthday registered.

The problem remains until the anniversary is removed again. Then the contact is fine.

**Comment by skjnldsv** [comment]
This is very strange, I'll try soon :)
Could you create a new issue with your find? This issue has many differents issue and starts to look confusing ;)

**Comment by pinowthebird** [comment]
Done. #501

**Comment by christian-weiss** [comment]
@DanLeonelli i have a very similar issue in #507 and some findings. Can you confirm my findings with your issue?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Comment by nepomuc** [comment]
I run into this error (`VCard object with uid already exists in this addressbook collection.`) for a few contacts. It seems like if they still get imported, but I can't be entirely sure. Can anyone explain what could cause this weird behaviour?
