### ISSUE TITLE
Please add a CHANGELOG.md file and link to it from apps.nextcloud.com

### ISSUE THREAD

**Issue by MagicFab** [nextcloud/contacts#996]
Contacts is a very important application in NextCloud, as such I'd like to know exactly what has changed since the last version when deciding if I'll upgrade it.

I'd like to suggest adding a proper CHANGELOG.md file to the project and linking to it from the Contacts app page at https://apps.nextcloud.com/apps/contacts .

**Comment by skjnldsv** [comment]
Done :)
I was updating the release page: https://github.com/nextcloud/contacts/releases

**Comment by MagicFab** [comment]
Thank you!

**Comment by klawdhfzasjhaa** [comment]
@skjnldsv:
Could you also add it to here: https://apps.nextcloud.com/apps/contacts/releases?platform=15#15?
This is the link you get to, when you are IN your nextcloud (admin page) and jump to the app.

See calendar for example: https://apps.nextcloud.com/apps/calendar/releases?platform=15#15.

**Comment by skjnldsv** [comment]
@klawdhfzasjhaa it will be done automatically on the further releases. Since it only recently been added onto contacts.

**Comment by klawdhfzasjhaa** [comment]
Hey! It's still not added to https://apps.nextcloud.com/apps/contacts/releases?platform=21#21 and that's why it is also not shown in the Updates section within Nextcloud. This would be very practical, because you wouldn't have to search github to read the release notes.

Can you please integrate it like here: https://apps.nextcloud.com/apps/notes/releases?platform=20?

**Comment by skjnldsv** [comment]
It is in the releases.
I guess it is not properly read by the appstore :thinking:

**Comment by klawdhfzasjhaa** [comment]
Strange. It looks good in <root>\CHANGELOG.md. Can you test it (with a not already updated system)?
